name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ✅ Confirm AWS_REGION is available
        run: |
          echo "✅ AWS_REGION is set to: $AWS_REGION"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (with confirmation)
        run: |
          echo "🔥 RUNNING terraform init -reconfigure"
          terraform init -reconfigure
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
